# Main option config
system:
  plugin_dir: /home/jjw/ddrpi/plugins

# Module layout config (we may change this later)
modules:
  1:
    width: 8
    height: 6
    x_position: 0
    y_position: 0
    orientation: N

  2:
    width: 8
    height: 6
    x_position: 0
    y_position: 5
    orientation: N

  3:
    width: 8
    height: 6
    x_position: 8
    y_position: 0
    orientation: E

  4:
    width: 8
    height: 6
    x_position: 7
    y_position: 7
    orientation: S

