# Main option config
system:
  width: 320
  height: 240

# Module layout config (we may change this later)
modules:
  1:
    width: 8
    height: 6
    x_position: 0
    y_position: 0
    x_origin: 0
    y_origin: 5
    direction: y

  2:
    width: 8
    height: 6
    x_position: 8
    y_position: 3
    x_origin: 15
    y_origin: 3
    direction: y

  4:
    width: 6
    height: 8
    x_position: 16
    y_position: 0
    x_origin: 21
    y_origin: 7
    direction: x

  3:
    width: 6
    height: 8
    x_position: 8
    y_position: 9
    x_origin: 8
    y_origin: 9
    direction: x

  5:
    width: 3
    height: 3
    x_position: 16
    y_position: 12
    x_origin: 16
    y_origin: 12
    direction: x

  6:
    width: 6
    height: 8
    x_position: 0
    y_position: 20
    x_origin: 0
    y_origin: 20
    direction: x

  7:
    width: 6
    height: 8
    x_position: 6
    y_position: 20
    x_origin: 6
    y_origin: 20
    direction: x

  8:
    width: 6
    height: 8
    x_position: 12
    y_position: 20
    x_origin: 12
    y_origin: 20
    direction: x

  9:
    width: 6
    height: 8
    x_position: 18
    y_position: 20
    x_origin: 18
    y_origin: 20
    direction: x
